name: options_app
description: Pro Activity Tracker with Analytics
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.0
  table_calendar: ^3.0.9

flutter:
  uses-material-design: true
